/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;//imported manualy
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;//imported manualy
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RH Shishir
 */
public class SCORE_GIVING extends javax.swing.JFrame {
    
    //////////variables
    String name,post,score;
    
    String gap="";
    JFileChooser jfc;
    File director;
    DefaultTableModel model;//table info shoing work
    File file=null;
    
    /**
     * Creates new form JFrame1st
     */
    public SCORE_GIVING() {
        initComponents();
        model = new DefaultTableModel();
        TABLE.setModel(model);
        model.addColumn("Name");
        model.addColumn("Post");
        model.addColumn("Score");
        
    }

    /**
     * 
     *  
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ACTUAL_Batton_GROUP1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        FOR_GIVING_NAME = new javax.swing.JTextField();
        FOR_SELECTING_MALE = new javax.swing.JRadioButton();
        FOR_SELECTING_FEMALE = new javax.swing.JRadioButton();
        jPanel3_TABLE_INFO = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1_SAVE = new javax.swing.JButton();
        FOR_CLEARING = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        FOR_SELECTING_POST = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Students Information");

        ACTUAL_Batton_GROUP1.add(FOR_SELECTING_MALE);
        FOR_SELECTING_MALE.setText("1");
        FOR_SELECTING_MALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOR_SELECTING_MALEActionPerformed(evt);
            }
        });

        ACTUAL_Batton_GROUP1.add(FOR_SELECTING_FEMALE);
        FOR_SELECTING_FEMALE.setText("3");
        FOR_SELECTING_FEMALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOR_SELECTING_FEMALEActionPerformed(evt);
            }
        });

        jButton1_SAVE.setText(" Save");
        jButton1_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SAVEActionPerformed(evt);
            }
        });

        FOR_CLEARING.setText("Clear");
        FOR_CLEARING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOR_CLEARINGActionPerformed(evt);
            }
        });

        EXIT.setText("Show helpers list");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Post", "Score"
            }
        ));
        jScrollPane1.setViewportView(TABLE);

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel6.setText("NOTE: save as \"helpers profile\"");

        BACK.setText("Back");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1_SAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(FOR_CLEARING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EXIT))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_SAVE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FOR_CLEARING)
                    .addComponent(EXIT)
                    .addComponent(BACK)))
        );

        javax.swing.GroupLayout jPanel3_TABLE_INFOLayout = new javax.swing.GroupLayout(jPanel3_TABLE_INFO);
        jPanel3_TABLE_INFO.setLayout(jPanel3_TABLE_INFOLayout);
        jPanel3_TABLE_INFOLayout.setHorizontalGroup(
            jPanel3_TABLE_INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_TABLE_INFOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        jPanel3_TABLE_INFOLayout.setVerticalGroup(
            jPanel3_TABLE_INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_TABLE_INFOLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        FOR_SELECTING_POST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Developer", "Web Desiner", "Management", "Software Engineer" }));

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel4.setText("Give Helper score");

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel3.setText("Select Helper post");

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel5.setText("Give Helper Name");

        ACTUAL_Batton_GROUP1.add(jRadioButton1);
        jRadioButton1.setText("5");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FOR_GIVING_NAME)
                    .addComponent(FOR_SELECTING_POST, 0, 263, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(FOR_SELECTING_MALE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FOR_SELECTING_FEMALE)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel3_TABLE_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FOR_GIVING_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FOR_SELECTING_POST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FOR_SELECTING_MALE)
                            .addComponent(FOR_SELECTING_FEMALE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel3_TABLE_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FOR_SELECTING_MALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOR_SELECTING_MALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FOR_SELECTING_MALEActionPerformed

    private void FOR_SELECTING_FEMALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOR_SELECTING_FEMALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FOR_SELECTING_FEMALEActionPerformed

    private void jButton1_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SAVEActionPerformed
        getting_all_record();
        //ERROR if name filed is empty
        if(FOR_GIVING_NAME.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Name");
            FOR_GIVING_NAME.requestFocus();
           }
        else{
            if(FOR_SELECTING_POST.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(rootPane, "Please Select Country");
                FOR_SELECTING_POST.requestFocus();
            }
            else{
                jfc = new JFileChooser(director);
                //adding file filter
                FileNameExtensionFilter filter;
                filter = new FileNameExtensionFilter("*.text",new String[]{"txt"});
                
                jfc.addChoosableFileFilter(filter);
                int option = jfc.showSaveDialog(this);
                if(option==JFileChooser.APPROVE_OPTION){
                    director=jfc.getCurrentDirectory();
                    model.addRow(new Object[]{name,post,score});
                    
                    file = jfc.getSelectedFile();
                    try {
                        for_saving();
                    } catch (IOException ex) {
                        //Logger.getLogger(JFrame1st.class.getName()).log(Level.SEVERE, null, ex);
                        ex.printStackTrace();
                   
                                
                    }
                   
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton1_SAVEActionPerformed

    private void FOR_CLEARINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOR_CLEARINGActionPerformed
        for_clearing();
    }//GEN-LAST:event_FOR_CLEARINGActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        new HELPING_WORKERS().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_EXITActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new HELP().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_BACKActionPerformed

private void getting_all_record(){
name = FOR_GIVING_NAME.getText();
//address = GIVING_ADRESS.getText();
post = FOR_SELECTING_POST.getSelectedItem().toString();
//radio button
if(FOR_SELECTING_MALE.isSelected()){
    score = "1";  
}
else if(FOR_SELECTING_MALE.isSelected()) {
    score = "2";
}
else{
    score = "5";
}
}
//////for saving
private void for_saving() throws IOException{
    BufferedWriter buf=null;
    try{
        buf = new BufferedWriter(new FileWriter(file+getExtension(),true));
        buf.write(name+","+post+","+score);
        buf.newLine();
        JOptionPane.showMessageDialog(rootPane, "Data Saved");
    } catch(Exception e){
        e.printStackTrace();  
    }
    finally{
        if(buf!=null){
            buf.close();
        }
    }        
    }
    private String getExtension(){
        String ext="";
        String extension = jfc.getFileFilter().getDescription();
        if(extension.equals("*.txt")){/////  /if user did not give .txt while saving
        ext = ".txt";
        
        }
        return ext;
    }
   
    
    private void for_clearing(){
        FOR_GIVING_NAME.setText("");
        //GIVING_ADRESS.setText("");
        FOR_SELECTING_POST.setSelectedIndex(0);
        
       
        if(TABLE.getRowCount()>0){
            for (int i = TABLE.getRowCount()-1; i > -1; i--) {
                model.removeRow(i);
            }
        }
       // TEXT_AREA.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCORE_GIVING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCORE_GIVING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCORE_GIVING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCORE_GIVING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCORE_GIVING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ACTUAL_Batton_GROUP1;
    private javax.swing.JButton BACK;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton FOR_CLEARING;
    private javax.swing.JTextField FOR_GIVING_NAME;
    private javax.swing.JRadioButton FOR_SELECTING_FEMALE;
    private javax.swing.JRadioButton FOR_SELECTING_MALE;
    private javax.swing.JComboBox<String> FOR_SELECTING_POST;
    private javax.swing.JTable TABLE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1_SAVE;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3_TABLE_INFO;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
